In [10]:
import numpy as np

In [11]:
def moving_avg(arr, w):         #defining the moving avrage funtion
    result=np.cumsum(arr)      # cummlative sum in a given list
    return (result[w:]-result[:-w])/float(w)    # moving average of the given list depends upon the window size

print('-'*30+'INPUT'+'-'*30)

window_size =int(input('Enter the window size: ' )) # Input of window size

arr= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]  # Given list

print('-'*30+'OUTPUT'+'-'*30)
      
print('The moving average of given array and window size is ',moving_avg(arr,window_size))  
                       

------------------------------INPUT------------------------------
Enter the window size: 3
------------------------------OUTPUT------------------------------
The moving average of given array and window size is  [  4.66666667   5.66666667   6.66666667   9.66666667  28.66666667
  49.33333333  72.66666667  84.          93.33333333 116.33333333]


Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [12]:


def matrix(a, n, increasing = True): #defining the matrix with two  input variables and one boolean function
    
    if increasing==True:
        
        return np.array([x**i for x in a for i in range(n)]).reshape(a.size,n)

    else:
        return np.array([x**(n-i-1) for x in a for i in range(n)]).reshape(a.size,n)

print('-'*30+'INPUT'+'-'*30)

n = int(input('Enter the length of the array : '))  # input of the length of the array

arr=[]  # empty list created

for i in range(n):
    
    x = int(input('Enter the value :'))   # input of each elemet 
    
    arr.append( x )                # input emlemets are added

print('The input list',arr)

nparray = np.array(arr)  # Input list is converted into numpy array of column of a input vector

print('-'*30+'OUTPUT'+'-'*30)


print('The power of the column in decreasing order')

print(matrix(nparray,n, False))

print('The power of the column in increasing order')

print(matrix(nparray,n, True))

------------------------------INPUT------------------------------
Enter the length of the array : 4
Enter the value :3
Enter the value :6
Enter the value :5
Enter the value :2
The input list [3, 6, 5, 2]
------------------------------OUTPUT------------------------------
The power of the column in decreasing order
[[ 27   9   3   1]
 [216  36   6   1]
 [125  25   5   1]
 [  8   4   2   1]]
The power of the column in increasing order
[[  1   3   9  27]
 [  1   6  36 216]
 [  1   5  25 125]
 [  1   2   4   8]]
