   #                     Assignment - 03

In [73]:
def div(a,b):   # defining the function div
    try:
        return a/b    # a is divisible by b
    except:
        return 'Sorry the number is not divisible by zero, try with other numbers '   # if the number is diveded by zero then it returns

    
print('-'*30+'INPUT'+'-'*30)

a = float(input('Enter the number of numerator: '))   # input of numerator
b = float(input('Enter the number of Denominator: '))  # input of denominator

print('-'*30+'OUTPUT'+'-'*30)
div(a,b)

------------------------------INPUT------------------------------
Enter the number of numerator: 5
Enter the number of Denominator: 0
------------------------OUTPUT------------------------


'Sorry the number is not divisible by zero, try with other numbers '

2.Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [74]:
subject = ['Americans', 'Indians']
verbs= ['play', 'watch']
objects = ['Baseball','Cricket']

lst =[(i+' '+j+' '+k+'.') for  i in subject for j in verbs for k in objects] 
for l in lst:
    print(l)
    

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


3.Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [76]:
import numpy as np

def matrix(a, n, increasing = True): #defining the matrix with two  input variables and one boolean function
    
    if increasing==True:
        
        return np.array([x**i for x in a for i in range(n)]).reshape(a.size,n)

    else:
        return np.array([x**(n-i-1) for x in a for i in range(n)]).reshape(a.size,n)

print('-'*30+'INPUT'+'-'*30)

n = int(input('Enter the length of the array : '))  # input of the length of the array

arr=[]  # empty list created

for i in range(n):
    
    x = int(input('Enter the value :'))   # input of each elemet 
    
    arr.append( x )                # input emlemets are added

print('The input list',arr)

nparray = np.array(arr)  # Input list is converted into numpy array of column of a input vector

print('-'*30+'OUTPUT'+'-'*30)


print('The power of the column in decreasing order')

print(matrix(nparray,n, False))

print('The power of the column in increasing order')

print(matrix(nparray,n, True))
    
    
    

------------------------------INPUT------------------------------
Enter the length of the array : 4
Enter the value :2
Enter the value :3
Enter the value :4
Enter the value :5
The input list [2, 3, 4, 5]
------------------------------OUTPUT------------------------------
The power of the column in decreasing order
[[  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
The power of the column in increasing order
[[  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
